# MySQL 数据库相关配置
db:
  host: 127.0.0.1
  username: root
  password: 1234qwer
  database: miniblog
  max-idle-connections: 100
  max-open-connections: 100
  max-connection-life-time: 10s
  log-level: 4


# 日志配置
log:
  disable-caller: false
  disable-stacktrace: false
  level: debug
  format: console
  output-paths: [/tmp/myblog.log, stdout]

addr: :8080 # HTTP 服务器监听地址

